version: "3.1"
services:
  redis:
    image: redis:6-alpine
    ports:
      - 6378:6379
    networks:
      - app_net
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    links:
      - fpm
    ports:
      - 8070:80
    networks:
      - app_net
    volumes:
      - ./docker/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: fpm
    links:
      - redis
    volumes:
      - ./.env:/var/www/html/.env
      - ./app:/var/www/html/app
      - ./storage:/var/www/html/storage
      - ./routes:/var/www/html/routes
      - ./config:/var/www/html/config
      - ./resources:/var/www/html/resources
      - ./public:/var/www/html/public
      - ./Modules:/var/www/html/Modules
      - ./database:/var/www/html/database
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
#      - ./vendor:/var/www/html/vendor # for working with vendor
    networks:
      - app_net

  postgres:
      build:
          context: ./docker/postgres
      ports:
          - 5433:5432
      volumes:
          - ./persistent-database:/var/lib/postgresql/data
      user: postgres:postgres
      environment:
          POSTGRES_USER: app_core_user
          POSTGRES_DB: app
          POSTGRES_PASSWORD: app_core_pass
      networks:
          - db_app_net

  php_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: php_worker
    links:
      - redis
    restart: always
    volumes:
      - ./docker/supervisor/queue.conf:/etc/supervisor/queue.conf
      - ./:/var/www/html/
    networks:
      - app_net

  schedule:
    build:
      context: .
      dockerfile: Dockerfile
      target: schedule
    restart: always
    volumes:
      - ./:/var/www/html/
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
volumes:
  pgdata1:
    driver: local
